'use client';
import { useState } from 'react';

export default function UserManager({ users }: { users: Array<{ id: number; username: string; email: string; role: 'USER' | 'ADMIN' }> }) {
  const [message, setMessage] = useState('');
  const create = async (form: FormData) => { const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(form)) }); const data = await response.json(); setMessage(data.success ? '用户已创建，刷新页面查看。' : data.error); };
  const update = async (user: { id: number; username: string; email: string; role: 'USER' | 'ADMIN' }) => { const username = window.prompt('用户名', user.username); if (username === null) return; const email = window.prompt('邮箱', user.email); if (email === null) return; const password = window.prompt('新密码（留空则不修改）', ''); if (password === null) return; const response = await fetch(`/api/admin/users/${user.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, email, password, role: user.role }) }); const data = await response.json(); setMessage(data.success ? '用户资料已更新，刷新页面查看。' : data.error); };
  const remove = async (id: number, username: string) => { if (window.prompt(`输入用户名 ${username} 以确认删除`) !== username) return; const response = await fetch(`/api/admin/users/${id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmUsername: username }) }); const data = await response.json(); setMessage(data.success ? '用户已删除，刷新页面查看。' : data.error); };
  return <><form action={async (form) => create(form)} style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 16 }}><input name="username" placeholder="用户名" required /><input name="email" type="email" placeholder="邮箱" required /><input name="password" type="password" placeholder="初始密码" minLength={6} required /><select name="role"><option value="USER">用户</option><option value="ADMIN">管理员</option></select><button className="btn btn-primary">新增用户</button></form>{message && <p>{message}</p>}<table><thead><tr><th>用户名</th><th>邮箱</th><th>角色</th><th>操作</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.username}</td><td>{user.email}</td><td>{user.role}</td><td><button className="btn" onClick={() => update(user)}>编辑/重置密码</button> <button className="btn" onClick={() => remove(user.id, user.username)}>删除</button></td></tr>)}</tbody></table></>;
}
